### ISSUE TITLE
Uninstalling app also deletes data and settings

### ISSUE THREAD

**Issue by devman16** [azmikemm/ZeoCompanion#10]
I recently switched from side-loaded to AppStore sourced installation so as to have notification of updates which required first uninstalling the side-loaded installation (repeated failure trying to install over the top).

This resulted in all journal data, attribute configuration and settings being deleted.

And, although I'm not sure about this, any previous backups have also been removed.  I'm positive that I'd performed some database backups using previous versions simply as a function of playing around with the interface, however I cannot find these backups now using ES Explorer.

Perhaps a notification to the user to ask if data should be exported or deleted could be implemented when triggered by the uninstallation process.

**Comment by azmikemm** [comment]
There is no mechanism for the App or a developer to control the uninstall process on an Android Device.  There is no installer/uninstaller file such as exists on Windows or Mac.  So I cannot add notifications about implications of uninstalling.

When an App is uninstalled, all the App's data is deleted.  Again, there is no control over this process.  For all Android and iOS Apps, if you delete any App, you lose all the data stored for that App resident on the device.

The point of creating the ZeoCompanion database backup in the external storage was to MOVE those backups off the Device and onto your computer.  Leaving a backup on the Android device is not a backup at all.  The device goes dead or gets stolen, your "backup" is also dead or stolen.  The backups must be moved off the device in order for the backups to be useful.

Using the Fire, if you had the Fire's backup and restore services enabled, that service may have a backup copy of the ZeoCompanion App and its data and its "external data" that you could restore.  However, its very unclear if these backup and restore utilities properly backup and restore the data of an App since Android 5.x.  However if backup/restore did a backup of your "external storage" area, then a copy of your ZeoCompanion database backup is likely in that backup, and you can use that to restore into the store-loaded ZeoCompanion App.

In terms of changing the App itself, I can see only three workarounds:
1.  Add a "nag" popup dialog when the backup button is pressed to remind the end-user to move the backup off the device in order for it to be secure and undeletable.  
2. Add an option for automatic email of the database backup emailed in addition to being put into "external storage".  My replicated databases are in the 2.5 MB range (they would be a lot smaller if the Zeo App database was not replicated within them) but still at some point the backup database file may become too big for some SMTP servers or email clients.
3. Finally, I can add a Setting to store the database backup in a different folder in the "root" of the "external storage" area.  I'm not 100% sure if those files are retained or deleted upon App deletion since their ownership meta-data still points to the App being uninstalled (even though the files are in a different non-App specific folder); I'm seeing conflicting information about that in the various forums.

**Comment by azmikemm** [comment]
Change 1: coded, tested, checked-in, ready for next release.
Change 3: coded, tested, checked-in, ready for next release; confirmed that App Uninstall will NOT delete backups stored in non-App specific folders.

**Comment by devman16** [comment]
Understood regarding Android uninstallation situation.  I figured there might be an event of some description that an author could subscribe to.

Regarding the Fire's 'Backup and Restore' feature, this isn't really amenable to use at the application level, rather applying to the system as a whole and at that it's only applied to new or factory restored instances.  C'est la vie.

I guess I was surprised by the deletion of the data since I was under the impression that an application's data is stored separately to the application itself.  Maybe it's a Fire thing.

**Comment by azmikemm** [comment]
All coding done and tested.  Ready for next release.
