### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by tekumara** [azmikemm/ZeoCompanion#15]
I open ZeoCompanion on my Google Pixel and just get a blank screen.

**Comment by jbuller** [comment]
Same here on Galaxy S8.
I uninstalled and then installed again and it works.
I think may be because I installed it first and then the Zeo Sleep Manager App afterwards which I could not get on the Google Play store but instead found at 
https://apkpure.com/zeo-sleep-manager/com.myzeo.android
https://www.apkmonk.com/app/com.myzeo.android/
