### ISSUE TITLE
Malformed email attachment naming for CSV files on auto export

### ISSUE THREAD

**Issue by devman16** [azmikemm/ZeoCompanion#6]
The MIME header for the CSV attachment appears to be malformed such that the attachment name is unable to be determined.

This is the raw header data from a recent email:
```
Content-Type: application/octet-stream; 
	name*0=ZeoCompanion_CSV_SS-myZeo-Minutes_2016-05-15-11-05-12.; 
	name*1=csv
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; 
	filename*0=ZeoCompanion_CSV_SS-myZeo-Minutes_2016-05-15-11-05-12.; 
	filename*1=csv
```
For reference, the corresponding header for the image file auto export is as follows:
```
Content-Type: image/png; 
	name=ZeoCompanion_Image_Standard_2016-05-15-11-05-13.png
Content-Transfer-Encoding: base64
Content-Disposition: attachment; 
	filename=ZeoCompanion_Image_Standard_2016-05-15-11-05-13.png
```
Refers to v1.0.2 Build 23 (from 'About' info)

**Comment by azmikemm** [comment]
Confirmed. I indeed already had this on my internal bug list.  I think its due to the filename being too long, as the CSV filenames were being properly encoded on earlier releases before I lengthened the filenames.

**Comment by azmikemm** [comment]
Problem was caused by the idiots that created the email specifications, specifically RFC 822 and RFC 2231.  Older email clients cannot understand RFC 2231's sad pathetic attempt to limit field lengths.  In the JavaMail library, I turned off foldtext and encodefilename.  The filename is now properly kept whole for older email clients to utilize.  I'm not sure if this will break some email clients though; I may have to add an Setting for this if other email clients sadly didn't forward proof-themselves from these inane antiquated specifications.

Coded.  Tested at least with Outlook 2007.
